markdown:    redcarpet
pygments:    true
permalink:   pretty
exclude:     ['less','future']
source:      docs
destination: docs/_gh_pages
encoding:    UTF-8
url:         http://teq-inc.github.io/cooker/
title:       Cooker

current_version:  0.1.3
repo:             https://github.com/teq-inc/cooker

download:
  source:         https://github.com/teq-inc/cooker/archive/master.zip