markdown:    redcarpet
pygments:    true
permalink:   pretty
exclude:     ['less','dist','bower_components','bower.json','.gitignore','Gruntfile.js','package.json','node_modules','README.md','validation-report.json','validation-status.json','future','js/future']
source:      ./
destination: ./_gh_pages
encoding:    UTF-8
url:         http://getbootstrap.com
title:       Cooker

current_version:  0.0.0
repo:             https://github.com/teq-inc/cooker

download:
  source:         https://github.com/teq-inc/cooker/archive/master.zip